In [0]:
! pip install transformers

In [0]:
from transformers import BertConfig, EncoderDecoderConfig, EncoderDecoderModel

# Initializing a BERT bert-base-uncased style configuration
config_encoder = BertConfig()
config_decoder = BertConfig()

config = EncoderDecoderConfig.from_encoder_decoder_configs(config_encoder, config_decoder)

# Initializing a Bert2Bert model from the bert-base-uncased style configurations
model = EncoderDecoderModel(config=config)

# Accessing the model configuration
config_encoder = model.config.encoder
config_decoder  = model.config.decoder

In [14]:
from transformers import EncoderDecoderModel, BertTokenizer
import torch

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = EncoderDecoderModel.from_encoder_decoder_pretrained('bert-base-uncased', 'bert-base-uncased') # initialize Bert2Bert

# forward
input_ids = torch.tensor(tokenizer.encode("Hello, my dog is cute", add_special_tokens=True)).unsqueeze(0)  # Batch size 1
outputs = model(input_ids=input_ids, decoder_input_ids=input_ids)
label = torch.tensor(tokenizer.encode("dog is cute", add_special_tokens=True)).unsqueeze(0)


# training
loss, outputs = model(input_ids=input_ids, decoder_input_ids=input_ids, lm_labels=label)[:2]

# generation
generated = model.generate(input_ids, decoder_start_token_id=model.config.decoder.pad_token_id)

ValueError: ignored

In [6]:
input_ids

tensor([[  101,  7592,  1010,  2026,  3899,  2003, 10140,   102]])

In [7]:
outputs

tensor([[[ -6.3390,  -6.3665,  -6.4600,  ...,  -5.5355,  -4.1787,  -5.8384],
         [ -6.0605,  -6.0980,  -6.1492,  ...,  -5.0190,  -3.6619,  -5.6481],
         [ -6.2835,  -6.1857,  -6.2198,  ...,  -5.8243,  -3.9650,  -4.2239],
         ...,
         [ -8.6994,  -8.6061,  -8.6930,  ...,  -8.4026,  -7.0615,  -6.1120],
         [ -7.7221,  -7.7373,  -7.7094,  ...,  -7.6440,  -6.1568,  -5.5106],
         [-13.5756, -13.0523, -12.9125,  ..., -10.4893, -11.9085,  -9.3556]]],
       grad_fn=<AddBackward0>)

In [8]:
outputs.shape

torch.Size([1, 8, 30522])

In [9]:
generated

tensor([[   0, 6506, 6506, 6506, 6506, 6506, 2666, 2666, 2666, 2666, 2666, 4618,
         4618, 4618, 4618, 4618, 4618, 4618, 4618, 4618]])

In [12]:
tokenizer.decode(generated[0])

'[PAD] leon leon leon leon leonieieieieie shall shall shall shall shall shall shall shall shall'

---

In [1]:
!pip install transformers

     |████████████████████████████████| 665kB 2.6MB/s 
     |████████████████████████████████| 3.8MB 6.9MB/s 
     |████████████████████████████████| 1.1MB 30.0MB/s 
     |████████████████████████████████| 890kB 44.2MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893260 sha256=baaa7edc9407c2fb8459cf0950e05e06815e72d326689238347e1e5e8ff6cc53
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [0]:
from  tokenizers import BertWordPieceTokenizer
tokenizer = BertWordPieceTokenizer()

In [3]:
tokenizer.encode('wow thats so cool')

Exception: ignored